version = 1

[envs.shell]
channels = ["conda-forge"]

[envs.shell.dependencies]
fzf = "*"
zoxide = "*"
bat = "*"
fd-find = "*"
rigrep = "*"
nvim = "*"
unibilium = "<2.1.4"

[envs.shell.exposed]
fzf = "fzf"
zoxide = "zoxide"
bat = "bat"
fd = "fd"
rg = "rg"
nvim = "nvim"
