#!/usr/bin/env bash

## 1. Search for text in files using Ripgrep
## 2. Interactively restart Ripgrep with reload action
## 3. Echo the file
vim=0
stack=0
while [ "$#" -gt 0 ]; do
    case "$1" in
    -s)
        stack=1
        shift 1
        ;;
    -v)
        vim=1
        shift 1
        ;;
    --)
        shift 1
        break
        ;;
    *)
        shift 1
        break
        ;;
    esac
done

if [ "$stack" -gt 0 ]; then
    RG_PREFIX="srg "
else
    RG_PREFIX="rg --column --line-number --no-heading --color=always -i "
fi

highlighter="--highlight-line {2}"
INITIAL_QUERY=""
ARGS="${@}"
selected=($(
    FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY") $ARGS" \
        fzf --ansi \
        --height 40% \
        --disabled --query "$INITIAL_QUERY" \
        --bind "change:reload:sleep 0.1; $RG_PREFIX {q} $ARGS || true" \
        --delimiter : \
        --preview "bat --color=always {1} ${highlighter}" \
        --preview-window 'left,50%,border-bottom,+{2}+3/3,~3'
))
IFS=':' read -a array <<<"$selected"
if [ "$vim" -gt 0 ]; then
    [ -n "${selected[0]}" ] && nvim "${array[0]}" "+${array[1]}"
else
    [ -n "${selected[0]}" ] && echo "${array[0]}"
fi
