#!/usr/bin/env bash
# srg ≣ Stacked ripgrep
# Sabarish 2023
# Stacked ripgrep stacks ripgrep searches, i.e.
#         srg "s1 s2"
# first searches for files containing 's1' and in the resulting list of files it searches for 's2'

# Set some defaults
globpars='*'
list_only=0

# Argparsing
while [ "$#" -gt 0 ]; do
    case "$1" in
    -g | --glob)
        globpars="$2"
        shift 2
        ;;
    -l | --list)
        list_only=1
        shift
        ;;
    *)
        string="$1"
        shift
        ;;
    esac
done

# Set the IFS to space
IFS=' '
# Use read to split the string into an array
read -ra myvar <<<"$string"

# rg through files with some specific extensions if needed
if [ "$globpars" = '*' ]; then
    var="rg '' -l -i  ${myvar[0]}"
else
    var="rg '' -l -i -g \"*.{$globpars}\" ${myvar[0]}"
fi

# repeatedly filter using for loop
for i in ${myvar[@]:1}; do
    var="${var}| xargs rg -i -l ${i} "
done
list=$(eval $var)
if [ "$list_only" -gt 0 ]; then
    echo "$list"
else
    list=$(echo $list | tr '\n' ' ')
    [ -n "${string// /}" ] && rg --column --line-number --no-heading --color=always -i ${myvar[-1]} ${list[@]} || :
fi
