#!/usr/bin/env bash

ctrl_c() {
    echo "Ctrl+C pressed!"
    exit 1
}

# Set the trap for the INT (SIGINT) signal
trap ctrl_c INT

while true; do
    aerospace list-windows --all |
        fzf --bind 'enter:execute(bash -c "aerospace focus --window-id {1}")+abort'
    sleep 0.2
done
