#!/usr/bin/env bash

ctrl_c() {
    echo "Ctrl+C pressed!"
    exit 1
}

# Set the trap for the INT (SIGINT) signal
trap ctrl_c INT

while true; do
    cat <(printf "Window ID | App Name | Monitor ID | App PID | App Bundle ID\n") \
        <(aerospace list-windows --all --format '%{window-id} | %{app-name} | %{monitor-id} | %{app-pid} | %{app-bundle-id}') | column -t -s '|' | fzf --header-lines=1 --bind 'enter:execute(bash -c "aerospace focus --window-id {1}")+abort'
    sleep 0.2
done
